# Generated by Django 5.2.16 on 2026-08-12 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('source_identifier', models.SlugField(max_length=80, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='websites/logos/')),
                ('primary_color', models.CharField(blank=True, default='#0F766E', max_length=20)),
                ('widget_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_name', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('secret_key', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='websites.website')),
            ],
            options={
                'verbose_name': 'Website API Key',
                'ordering': ['-created_at'],
            },
        ),
    ]
