# Generated by Django 5.2.16 on 2026-10-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google (Gemini)')], default='anthropic', max_length=20)),
                ('model', models.CharField(default='claude-opus-5-5', max_length=100)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
