# Generated by Django 5.2.16 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_ai_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='agent_idle_minutes',
            field=models.PositiveIntegerField(default=0, help_text='If the agent leaves a customer message unanswered this long, the AI resumes.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='handoff_wait_minutes',
            field=models.PositiveIntegerField(default=15, help_text='If nobody picks up a handoff within this many minutes, the AI resumes.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='handoff_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
