# Generated by Django 5.2.16 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_aisettings_agent_idle_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='landing_page',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='conversation',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='conversation',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
