# Generated by Django 5.2.16 on 2026-10-07 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_attribution'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('cancellation', 'Cancellation'), ('payment', 'Payment'), ('faq', 'FAQ'), ('travel_info', 'Travel information'), ('other', 'Other')], default='faq', max_length=20)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated words or phrases customers use for this, e.g. “refund, cancel, money back”. Lets the rule-based replies find it.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, help_text='Leave blank to use it on every website.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='websites.website')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
