# Generated by Django 5.2.16 on 2026-10-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Also email lead, handoff, payment and follow-up notifications.'),
        ),
    ]
