# Generated by Django 5.2.16 on 2026-10-07 05:23

from datetime import timedelta

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def skip_stale_reminders(apps, schema_editor):
    """Reminders that were due more than a day before reminders existed stay quiet.

    Otherwise the first scheduler run would mail every old open task at once.
    They still show as overdue on the Follow-ups page.
    """
    task_model = apps.get_model("crm", "FollowUpTask")
    now = timezone.now()
    cutoff = now - timedelta(days=1)
    task_model.objects.filter(is_completed=False).filter(
        Q(reminder_at__lt=cutoff) | Q(reminder_at__isnull=True, due_at__lt=cutoff)
    ).update(reminded_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuptask',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(skip_stale_reminders, migrations.RunPython.noop),
    ]
