# Generated by Django 5.2.16 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_refund_status_webhook_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
