# Generated by Django 5.2.16 on 2026-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_payment_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='landing_page',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
