# Generated by Django 5.2.16 on 2026-10-07 07:59

from django.db import migrations, models

# Nothing ever wrote these two, but map any stray rows before the choices go:
# a draft was never charged (pending payment); "paid" meant money captured.
LEGACY = {"draft": "pending", "paid": "confirmed"}


def forwards(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for old, new in LEGACY.items():
        Booking.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_attribution'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
